window.PLAYER_POOL = [
  {
    id: "lionel-messi",
    name: "Lionel Messi",
    stats: { matches: 1084, assists: 386, titles: 44, goals: 838 },
    hint: "A left foot people still talk about.",
    hintPt: "Um pé esquerdo que ainda rende conversa.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["argentina", "argentinian", "argentino"],
      position: ["forward", "winger", "playmaker"],
      clubs: ["barcelona", "psg", "inter miami", "newells old boys"],
      leagues: ["la liga", "ligue 1", "mls"],
      shirtNumbers: ["10", "19", "30"],
      nicknames: ["la pulga", "goat", "leo"],
      hair: ["dark hair", "brown hair", "beard"],
      traits: ["left-footed", "short", "bearded", "captain"],
      personal: ["antonela roccuzzo", "rosario"],
      achievements: [
        "world cup",
        "copa america",
        "ballon dor",
        "champions league"
      ]
    }
  },
  {
    id: "cristiano-ronaldo",
    name: "Cristiano Ronaldo",
    stats: { matches: 1240, assists: 268, titles: 35, goals: 895 },
    hint: "One number became larger than life.",
    hintPt: "Um número ficou maior que a própria camisa.",
    personalStatus: "not-married",
    personalChildren: 5,
    facts: {
      nationality: ["portugal", "portuguese"],
      position: ["forward", "striker", "winger"],
      clubs: ["sporting", "manchester united", "real madrid", "juventus", "al nassr"],
      leagues: ["premier league", "la liga", "serie a", "saudi pro league"],
      shirtNumbers: ["7", "9", "17", "28"],
      nicknames: ["cr7"],
      hair: ["dark hair", "short hair"],
      traits: ["right-footed", "captain", "tall"],
      personal: ["georgina rodriguez", "madeira"],
      achievements: ["euro", "nations league", "ballon dor", "champions league"]
    }
  },
  {
    id: "neymar",
    name: "Neymar Jr.",
    stats: { matches: 733, assists: 215, titles: 31, goals: 439 },
    hint: "Style first, always.",
    hintPt: "Estilo em primeiro lugar, sempre.",
    personalStatus: "not-married",
    personalChildren: 1,
    facts: {
      nationality: ["brazil", "brazilian", "brasil"],
      position: ["forward", "winger", "playmaker"],
      clubs: ["santos", "barcelona", "psg", "al hilal"],
      leagues: ["brazilian serie a", "la liga", "ligue 1", "saudi pro league"],
      shirtNumbers: ["10", "11"],
      nicknames: ["ney"],
      hair: ["dark hair", "blond hair"],
      traits: ["right-footed", "tattooed"],
      personal: ["mogi das cruzes"],
      achievements: ["champions league", "olympic gold", "copa libertadores"]
    }
  },
  {
    id: "zlatan-ibrahimovic",
    name: "Zlatan Ibrahimovic",
    stats: { matches: 988, assists: 205, titles: 34, goals: 573 },
    hint: "Confidence was part of the show.",
    hintPt: "A confiança também fazia parte do espetáculo.",
    personalStatus: "not-married",
    personalChildren: 2,
    facts: {
      nationality: ["sweden", "swedish", "suecia"],
      position: ["striker", "forward"],
      clubs: ["malmo", "ajax", "juventus", "inter", "barcelona", "milan", "psg", "manchester united", "la galaxy"],
      leagues: ["eredvisie", "serie a", "la liga", "ligue 1", "premier league", "mls"],
      shirtNumbers: ["9", "10", "11", "18", "21"],
      nicknames: ["ibra"],
      hair: ["dark hair", "ponytail", "goatee"],
      traits: ["tall", "right-footed"],
      personal: ["helena seger", "malmo"],
      achievements: ["europa league"]
    }
  },
  {
    id: "kylian-mbappe",
    name: "Kylian Mbappe",
    stats: { matches: 469, assists: 150, titles: 18, goals: 328 },
    hint: "Everything moves fast around him.",
    hintPt: "Tudo parece acontecer rápido ao redor dele.",
    personalStatus: "not-married",
    personalChildren: 0,
    facts: {
      nationality: ["france", "french", "franca", "frances"],
      position: ["forward", "striker", "winger"],
      clubs: ["monaco", "psg", "real madrid"],
      leagues: ["ligue 1", "la liga"],
      shirtNumbers: ["7", "10", "29"],
      nicknames: ["donatello"],
      hair: ["short hair", "dark hair"],
      traits: ["right-footed", "fast", "captain"],
      personal: ["bondy"],
      achievements: ["world cup", "nations league"]
    }
  },
  {
    id: "ronaldinho",
    name: "Ronaldinho",
    stats: { matches: 853, assists: 197, titles: 21, goals: 313 },
    hint: "Joy was never hidden.",
    hintPt: "A alegria nunca ficou escondida.",
    personalStatus: "not-married",
    personalChildren: 1,
    facts: {
      nationality: ["brazil", "brazilian", "brasil"],
      position: ["attacking midfielder", "forward", "winger", "playmaker"],
      clubs: ["gremio", "psg", "barcelona", "milan", "flamengo", "atletico mineiro", "queretaro", "fluminense"],
      leagues: ["brazilian serie a", "ligue 1", "la liga", "serie a", "liga mx"],
      shirtNumbers: ["10", "11", "49", "80"],
      nicknames: ["gaucho", "ronnie"],
      hair: ["long hair", "dark hair"],
      traits: ["right-footed", "smiling"],
      personal: ["porto alegre"],
      achievements: ["world cup", "ballon dor", "champions league", "copa libertadores"]
    }
  },
  {
    id: "david-beckham",
    name: "David Beckham",
    stats: { matches: 718, assists: 214, titles: 19, goals: 127 },
    hint: "Precision met spotlight.",
    hintPt: "Precisão encontrou holofote.",
    personalStatus: "married",
    personalChildren: 4,
    facts: {
      nationality: ["england", "english", "british", "inglaterra", "ingles"],
      position: ["midfielder", "right midfielder"],
      clubs: ["manchester united", "real madrid", "la galaxy", "milan", "psg"],
      leagues: ["premier league", "la liga", "mls", "serie a", "ligue 1"],
      shirtNumbers: ["7", "10", "23", "32"],
      nicknames: ["becks"],
      hair: ["blond hair", "mohawk", "short hair"],
      traits: ["right-footed", "tattooed"],
      personal: ["victoria beckham", "london"],
      achievements: ["champions league", "treble"]
    }
  },
  {
    id: "sergio-ramos",
    name: "Sergio Ramos",
    stats: { matches: 837, assists: 58, titles: 29, goals: 117 },
    hint: "He liked the last word.",
    hintPt: "Ele gostava de ter a última palavra.",
    personalStatus: "married",
    personalChildren: 4,
    facts: {
      nationality: ["spain", "spanish", "espanha", "espanhol"],
      position: ["defender", "centre-back", "right-back"],
      clubs: ["sevilla", "real madrid", "psg"],
      leagues: ["la liga", "ligue 1"],
      shirtNumbers: ["4", "15", "21"],
      nicknames: ["sr4"],
      hair: ["long hair", "dark hair", "beard"],
      traits: ["right-footed", "captain", "tattooed"],
      personal: ["pilar rubio", "camas"],
      achievements: ["world cup", "euro", "champions league"]
    }
  },
  {
    id: "andres-iniesta",
    name: "Andres Iniesta",
    stats: { matches: 1016, assists: 153, titles: 37, goals: 106 },
    hint: "Calm never left his game.",
    hintPt: "A calma nunca saiu do jogo dele.",
    personalStatus: "married",
    personalChildren: 5,
    facts: {
      nationality: ["spain", "spanish", "espanha", "espanhol"],
      position: ["midfielder", "central midfielder", "attacking midfielder"],
      clubs: ["barcelona", "vissel kobe", "emirates club"],
      leagues: ["la liga", "j league", "uae pro league"],
      shirtNumbers: ["6", "8", "24"],
      nicknames: ["don andres"],
      hair: ["bald"],
      traits: ["right-footed", "captain", "playmaker"],
      personal: ["anna ortiz", "fuentealbilla"],
      achievements: ["world cup", "euro", "champions league"]
    }
  },
  {
    id: "karim-benzema",
    name: "Karim Benzema",
    stats: { matches: 861, assists: 166, titles: 34, goals: 451 },
    hint: "Patience paid off late.",
    hintPt: "A paciência cobrou seu prêmio no fim.",
    personalStatus: "not-married",
    personalChildren: 4,
    facts: {
      nationality: ["france", "french", "franca", "frances"],
      position: ["striker", "forward"],
      clubs: ["lyon", "real madrid", "al ittihad"],
      leagues: ["ligue 1", "la liga", "saudi pro league"],
      shirtNumbers: ["9", "10", "19"],
      nicknames: ["benz"],
      hair: ["dark hair", "beard", "short hair"],
      traits: ["right-footed", "captain"],
      personal: ["lyon"],
      achievements: ["ballon dor", "champions league", "nations league"]
    }
  },
  {
    id: "luka-modric",
    name: "Luka Modric",
    stats: { matches: 916, assists: 151, titles: 34, goals: 124 },
    hint: "The tempo often belonged to him.",
    hintPt: "O ritmo muitas vezes pertencia a ele.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["croatia", "croatian", "croacia", "croata"],
      position: ["midfielder", "central midfielder", "playmaker"],
      clubs: ["dinamo zagreb", "tottenham", "real madrid"],
      leagues: ["croatian first league", "premier league", "la liga"],
      shirtNumbers: ["10", "14", "19"],
      nicknames: ["lukita"],
      hair: ["long hair", "blond hair"],
      traits: ["right-footed", "captain"],
      personal: ["vanja bosnic", "zadar"],
      achievements: ["ballon dor", "champions league"]
    }
  },
  {
    id: "paolo-maldini",
    name: "Paolo Maldini",
    stats: { matches: 902, assists: 33, titles: 26, goals: 39 },
    hint: "Some careers never needed a second home.",
    hintPt: "Algumas carreiras nunca precisaram de segunda casa.",
    personalStatus: "married",
    personalChildren: 2,
    facts: {
      nationality: ["italy", "italian", "italia", "italiano"],
      position: ["defender", "left-back", "centre-back"],
      clubs: ["milan"],
      leagues: ["serie a"],
      shirtNumbers: ["3"],
      nicknames: ["il capitano"],
      hair: ["long hair", "dark hair"],
      traits: ["left-footed", "captain", "one-club man"],
      personal: ["adriana fossa", "milan"],
      achievements: ["champions league"]
    }
  },
  {
    id: "pele",
    name: "Pele",
    stats: { matches: 812, assists: 131, titles: 26, goals: 757 },
    hint: "The crown came early and stayed.",
    hintPt: "A coroa chegou cedo e ficou.",
    personalStatus: "married",
    personalChildren: 7,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["forward", "striker"],
      clubs: ["santos", "new york cosmos"],
      leagues: ["brazilian serie a", "nasl"],
      shirtNumbers: ["10"],
      nicknames: ["o rei", "king pele"],
      hair: ["dark hair"],
      traits: ["right-footed"],
      personal: ["tres coracoes", "edson arantes do nascimento"],
      achievements: ["world cup"]
    }
  },
  {
    id: "diego-maradona",
    name: "Diego Maradona",
    stats: { matches: 588, assists: 107, titles: 11, goals: 312 },
    hint: "For some cities, memory is not enough.",
    hintPt: "Para algumas cidades, memória é pouco.",
    personalStatus: "married",
    personalChildren: 5,
    facts: {
      nationality: ["argentina", "argentinian", "argentino"],
      position: ["playmaker", "attacking midfielder", "forward"],
      clubs: ["argentinos juniors", "boca juniors", "barcelona", "napoli", "sevilla", "newells old boys"],
      leagues: ["argentine primera", "la liga", "serie a"],
      shirtNumbers: ["10"],
      nicknames: ["el pibe de oro"],
      hair: ["dark hair"],
      traits: ["left-footed", "short"],
      personal: ["villa fiorito"],
      achievements: ["world cup", "uefa cup"]
    }
  },
  {
    id: "ronaldo-nazario",
    name: "Ronaldo Nazario",
    stats: { matches: 616, assists: 102, titles: 18, goals: 414 },
    hint: "At full speed, panic followed.",
    hintPt: "Em velocidade máxima, o pânico vinha junto.",
    personalStatus: "married",
    personalChildren: 4,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["striker", "forward"],
      clubs: ["cruzeiro", "psv", "barcelona", "inter", "real madrid", "milan", "corinthians"],
      leagues: ["brazilian serie a", "eredvisie", "la liga", "serie a"],
      shirtNumbers: ["9", "10", "11"],
      nicknames: ["fenomeno", "o fenomeno"],
      hair: ["bald"],
      traits: ["right-footed"],
      personal: ["rio de janeiro"],
      achievements: ["world cup", "ballon dor", "copa america"]
    }
  },
  {
    id: "romario",
    name: "Romario",
    stats: { matches: 893, assists: 97, titles: 18, goals: 756 },
    hint: "Few touches were ever wasted.",
    hintPt: "Poucos toques foram desperdiçados.",
    personalStatus: "not-married",
    personalChildren: 6,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["striker", "forward"],
      clubs: ["vasco", "psv", "barcelona", "flamengo", "fluminense"],
      leagues: ["brazilian serie a", "eredvisie", "la liga"],
      shirtNumbers: ["11"],
      nicknames: ["baixinho"],
      hair: ["dark hair"],
      traits: ["right-footed", "short"],
      personal: ["rio de janeiro"],
      achievements: ["world cup", "copa america"]
    }
  },
  {
    id: "rivaldo",
    name: "Rivaldo",
    stats: { matches: 770, assists: 130, titles: 20, goals: 377 },
    hint: "Improvisation felt natural to him.",
    hintPt: "A improvisação parecia natural para ele.",
    personalStatus: "married",
    personalChildren: 5,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["forward", "attacking midfielder", "playmaker"],
      clubs: ["palmeiras", "deportivo la coruna", "barcelona", "milan", "olympiacos"],
      leagues: ["brazilian serie a", "la liga", "serie a", "super league greece"],
      shirtNumbers: ["10", "11"],
      nicknames: ["riva"],
      hair: ["bald"],
      traits: ["left-footed"],
      personal: ["paulista"],
      achievements: ["world cup", "ballon dor", "champions league"]
    }
  },
  {
    id: "roberto-carlos",
    name: "Roberto Carlos",
    stats: { matches: 1040, assists: 113, titles: 25, goals: 113 },
    hint: "The ball did unusual things for him.",
    hintPt: "A bola fazia coisas estranhas por ele.",
    personalStatus: "married",
    personalChildren: 11,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["defender", "left-back"],
      clubs: ["palmeiras", "inter", "real madrid", "fenerbahce", "corinthians", "anzhi"],
      leagues: ["brazilian serie a", "serie a", "la liga", "super lig"],
      shirtNumbers: ["3", "6"],
      nicknames: ["rc3"],
      hair: ["bald"],
      traits: ["left-footed", "fast"],
      personal: ["garca"],
      achievements: ["world cup", "champions league", "copa america"]
    }
  },
  {
    id: "cafu",
    name: "Cafu",
    stats: { matches: 896, assists: 87, titles: 20, goals: 41 },
    hint: "He never seemed to run out.",
    hintPt: "Parecia não acabar nunca.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["defender", "right-back"],
      clubs: ["sao paulo", "zaragoza", "palmeiras", "roma", "milan"],
      leagues: ["brazilian serie a", "la liga", "serie a"],
      shirtNumbers: ["2"],
      nicknames: ["pendolino"],
      hair: ["dark hair"],
      traits: ["right-footed", "captain", "fast"],
      personal: ["sao paulo"],
      achievements: ["world cup", "champions league", "copa america"]
    }
  },
  {
    id: "xavi",
    name: "Xavi",
    stats: { matches: 1031, assists: 219, titles: 33, goals: 125 },
    hint: "He moved the match without moving much.",
    hintPt: "Ele mexia no jogo sem parecer correr tanto.",
    personalStatus: "married",
    personalChildren: 2,
    facts: {
      nationality: ["spain", "spanish", "espanha", "espanhol"],
      position: ["midfielder", "central midfielder", "playmaker"],
      clubs: ["barcelona", "al sadd"],
      leagues: ["la liga", "qatar stars league"],
      shirtNumbers: ["6", "8"],
      nicknames: ["xavineta"],
      hair: ["short hair", "dark hair"],
      traits: ["right-footed", "playmaker", "captain"],
      personal: ["terrassa"],
      achievements: ["world cup", "euro", "champions league"]
    }
  },
  {
    id: "thierry-henry",
    name: "Thierry Henry",
    stats: { matches: 915, assists: 174, titles: 18, goals: 411 },
    hint: "Grace and danger arrived together.",
    hintPt: "Graça e perigo chegavam juntos.",
    personalStatus: "not-married",
    personalChildren: 1,
    facts: {
      nationality: ["france", "french", "franca", "frances"],
      position: ["forward", "striker", "winger"],
      clubs: ["monaco", "juventus", "arsenal", "barcelona", "new york red bulls"],
      leagues: ["ligue 1", "serie a", "premier league", "la liga", "mls"],
      shirtNumbers: ["12", "14"],
      nicknames: ["titi"],
      hair: ["bald"],
      traits: ["right-footed", "fast"],
      personal: ["les ulis"],
      achievements: ["world cup", "euro", "champions league"]
    }
  },
  {
    id: "wayne-rooney",
    name: "Wayne Rooney",
    stats: { matches: 883, assists: 146, titles: 16, goals: 366 },
    hint: "Raw edge was part of the package.",
    hintPt: "A aspereza fazia parte do pacote.",
    personalStatus: "married",
    personalChildren: 4,
    facts: {
      nationality: ["england", "english", "inglaterra", "ingles"],
      position: ["forward", "striker", "attacking midfielder"],
      clubs: ["everton", "manchester united", "dc united", "derby county"],
      leagues: ["premier league", "mls", "championship"],
      shirtNumbers: ["8", "9", "10", "18"],
      nicknames: ["wazza"],
      hair: ["short hair", "dark hair"],
      traits: ["right-footed"],
      personal: ["liverpool", "coleen rooney"],
      achievements: ["champions league", "premier league"]
    }
  },
  {
    id: "kaka",
    name: "Kaka",
    stats: { matches: 717, assists: 142, titles: 16, goals: 237 },
    hint: "Smooth can still be direct.",
    hintPt: "Suavidade também pode ser vertical.",
    personalStatus: "not-married",
    personalChildren: 2,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["attacking midfielder", "playmaker", "forward"],
      clubs: ["sao paulo", "milan", "real madrid", "orlando city"],
      leagues: ["brazilian serie a", "serie a", "la liga", "mls"],
      shirtNumbers: ["8", "10", "22"],
      nicknames: ["kaka"],
      hair: ["dark hair", "short hair"],
      traits: ["right-footed", "captain"],
      personal: ["gama", "brasilia"],
      achievements: ["world cup", "ballon dor", "champions league"]
    }
  },
  {
    id: "juninho-pernambucano",
    name: "Juninho Pernambucano",
    stats: { matches: 760, assists: 166, titles: 16, goals: 181 },
    hint: "Stillness before the strike mattered.",
    hintPt: "O silêncio antes da batida dizia muito.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["midfielder", "central midfielder", "playmaker"],
      clubs: ["sport do recife", "vasco", "lyon", "al gharafa", "new york red bulls"],
      leagues: ["brazilian serie a", "ligue 1", "qatar stars league", "mls"],
      shirtNumbers: ["8", "10"],
      nicknames: ["juninho"],
      hair: ["dark hair", "short hair"],
      traits: ["right-footed", "captain"],
      personal: ["recife"],
      achievements: ["confederations cup", "ligue 1"]
    }
  },
  {
    id: "deco",
    name: "Deco",
    stats: { matches: 679, assists: 126, titles: 25, goals: 112 },
    hint: "Control came without noise.",
    hintPt: "O controle vinha sem barulho.",
    personalStatus: "married",
    personalChildren: 5,
    facts: {
      nationality: ["portugal", "portuguese", "brazil", "brazilian"],
      position: ["midfielder", "playmaker", "attacking midfielder"],
      clubs: ["porto", "barcelona", "chelsea", "fluminense"],
      leagues: ["primeira liga", "la liga", "premier league", "brazilian serie a"],
      shirtNumbers: ["10", "20"],
      nicknames: ["deco"],
      hair: ["dark hair", "short hair"],
      traits: ["right-footed"],
      personal: ["sao bernardo do campo"],
      achievements: ["champions league", "euro"]
    }
  },
  {
    id: "dida",
    name: "Dida",
    stats: { matches: 781, assists: 1, titles: 24, goals: 0 },
    hint: "Calm looked tall here.",
    hintPt: "A calma aqui parecia alta.",
    personalStatus: "married",
    personalChildren: 2,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["goalkeeper", "goleiro"],
      clubs: ["vitoria", "cruzeiro", "milan", "corinthians", "internacional"],
      leagues: ["brazilian serie a", "serie a"],
      shirtNumbers: ["1", "12"],
      nicknames: ["dida"],
      hair: ["dark hair"],
      traits: ["right-footed", "tall"],
      personal: ["irara"],
      achievements: ["world cup", "champions league", "copa america"]
    }
  },
  {
    id: "claude-makelele",
    name: "Claude Makelele",
    stats: { matches: 917, assists: 32, titles: 18, goals: 25 },
    hint: "He made invisible work unforgettable.",
    hintPt: "Ele tornou inesquecível um trabalho quase invisível.",
    personalStatus: "not-married",
    personalChildren: 1,
    facts: {
      nationality: ["france", "french", "franca", "frances"],
      position: ["midfielder", "defensive midfielder"],
      clubs: ["nantes", "marseille", "celta vigo", "real madrid", "chelsea", "psg"],
      leagues: ["ligue 1", "la liga", "premier league"],
      shirtNumbers: ["4", "6"],
      nicknames: ["make"],
      hair: ["bald"],
      traits: ["right-footed"],
      personal: ["kinshasa"],
      achievements: ["champions league", "premier league", "la liga"]
    }
  },
  {
    id: "michael-laudrup",
    name: "Michael Laudrup",
    stats: { matches: 826, assists: 188, titles: 24, goals: 186 },
    hint: "Purists usually smile first.",
    hintPt: "Os puristas costumam sorrir primeiro.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["denmark", "danish", "dinamarca", "dinamarques"],
      position: ["playmaker", "attacking midfielder", "forward"],
      clubs: ["brondby", "lazio", "juventus", "barcelona", "real madrid", "ajax"],
      leagues: ["superliga", "serie a", "la liga", "eredvisie"],
      shirtNumbers: ["10", "11"],
      nicknames: ["laudrup"],
      hair: ["dark hair"],
      traits: ["right-footed"],
      personal: ["copenhagen"],
      achievements: ["european cup", "la liga"]
    }
  },
  {
    id: "pavel-nedved",
    name: "Pavel Nedved",
    stats: { matches: 760, assists: 102, titles: 14, goals: 145 },
    hint: "Endurance met edge.",
    hintPt: "Resistência encontrou intensidade.",
    personalStatus: "married",
    personalChildren: 2,
    facts: {
      nationality: ["czech republic", "czech", "republica tcheca", "tcheco"],
      position: ["midfielder", "winger", "playmaker"],
      clubs: ["sparta prague", "lazio", "juventus"],
      leagues: ["czech first league", "serie a"],
      shirtNumbers: ["11", "18"],
      nicknames: ["the czech fury"],
      hair: ["blond hair", "long hair"],
      traits: ["left-footed", "captain"],
      personal: ["cheb"],
      achievements: ["ballon dor", "serie a"]
    }
  },
  {
    id: "davor-suker",
    name: "Davor Suker",
    stats: { matches: 641, assists: 61, titles: 8, goals: 322 },
    hint: "One tournament can echo for decades.",
    hintPt: "Um torneio pode ecoar por décadas.",
    personalStatus: "not-married",
    personalChildren: 0,
    facts: {
      nationality: ["croatia", "croatian", "croacia", "croata"],
      position: ["striker", "forward"],
      clubs: ["osijek", "dinamo zagreb", "sevilla", "real madrid", "arsenal", "west ham", "1860 munich"],
      leagues: ["croatian first league", "la liga", "premier league", "bundesliga"],
      shirtNumbers: ["9", "10"],
      nicknames: ["suki"],
      hair: ["dark hair"],
      traits: ["left-footed"],
      personal: ["osijek"],
      achievements: ["world cup golden boot", "champions league"]
    }
  },
  {
    id: "socrates",
    name: "Socrates",
    stats: { matches: 635, assists: 109, titles: 10, goals: 172 },
    hint: "Brains were visible in the style.",
    hintPt: "A inteligência aparecia até no estilo.",
    personalStatus: "married",
    personalChildren: 6,
    facts: {
      nationality: ["brazil", "brazilian", "brasil", "brasileiro"],
      position: ["midfielder", "playmaker", "attacking midfielder"],
      clubs: ["botafogo sp", "corinthians", "fiorentina", "flamengo", "santos"],
      leagues: ["brazilian serie a", "serie a"],
      shirtNumbers: ["8"],
      nicknames: ["doctor", "magrao"],
      hair: ["dark hair", "beard"],
      traits: ["right-footed", "tall", "captain", "bearded"],
      personal: ["belem do para"],
      achievements: ["campeonato paulista"]
    }
  },
  {
    id: "valderrama",
    name: "Carlos Valderrama",
    stats: { matches: 777, assists: 167, titles: 7, goals: 94 },
    hint: "The silhouette alone says a lot.",
    hintPt: "A silhueta sozinha já diz bastante.",
    personalStatus: "married",
    personalChildren: 3,
    facts: {
      nationality: ["colombia", "colombian", "colombia", "colombiano"],
      position: ["midfielder", "playmaker"],
      clubs: ["union magdalena", "montpellier", "real valladolid", "independiente medellin", "tampa bay mutiny", "miami fusion", "colorado rapids"],
      leagues: ["colombian primera a", "ligue 1", "la liga", "mls"],
      shirtNumbers: ["10"],
      nicknames: ["el pibe"],
      hair: ["blond hair", "long hair"],
      traits: ["right-footed"],
      personal: ["santa marta"],
      achievements: ["copa america third place"]
    }
  }
];
